name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.2.3)'
        required: true

jobs:
  upload-release-assets:
    name: Upload Release Assets
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Version Check
        run: make check-version tag=${{ github.event.inputs.tag || github.ref }}

      - name: Tarball
        run: make release

      - name: Upload Release Assets
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('${{ github.workspace }}/.github/upload-release-assets.js')
            const tag = '${{ github.event.inputs.tag || github.ref }}'
            await script({ context, github }, tag)
